"""empty message

Revision ID: 415441262aae
Revises: 2e97f4b49e1a
Create Date: 2018-03-30 17:33:53.327766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415441262aae'
down_revision = '2e97f4b49e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('som_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'som_week')
    # ### end Alembic commands ###
