"""
First commit

Revision ID: a504e348d6a9
Revises: 
Create Date: 2018-02-08 22:20:45.364431

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a504e348d6a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'accounts',
        sa.Column('owner', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('owner')
    )
    op.create_table(
        'posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('permlink', sa.String(), nullable=False),
        sa.Column('block_number', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('tags', sa.String(), nullable=False),
        sa.Column('is_nsfw', sa.Boolean(), nullable=False),
        sa.Column('has_declined_payout', sa.Boolean(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('has_paidout', sa.Boolean(), nullable=False),
        sa.Column('pending_payout_value', sa.Numeric(), nullable=True),
        sa.Column('total_payout_value', sa.Numeric(), nullable=True),
        sa.Column('steem_json', sa.JSON(), nullable=True),
        sa.Column('video_type', sa.String(), nullable=True),
        sa.Column('video_id', sa.String(), nullable=True),
        sa.Column('video_info', sa.JSON(), nullable=True),
        sa.Column('trending_score', sa.Integer(), nullable=True),
        sa.Column('hot_score', sa.Integer(), nullable=True),
        sa.Column('other_score', sa.Integer(), nullable=True),
        sa.Column('steem_thumbnail_image_url', sa.String(), nullable=True),
        sa.Column('video_thumbnail_image_url', sa.String(), nullable=True),
        sa.Column('video_provider_channel_id', sa.String(), nullable=True),
        sa.Column('video_duration_seconds', sa.Integer(), nullable=True),
        sa.Column('video_post_publish_delay_seconds', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('voters_list', sa.String(), nullable=True),
        sa.Column('votes_sparkline_data', sa.JSON(), nullable=True),
        sa.Column('pending_steem_info_update', sa.Boolean(), nullable=False),
        sa.Column('pending_video_info_update', sa.Boolean(), nullable=False),
        sa.Column('steem_info_update_requested', sa.DateTime(), nullable=True),
        sa.Column('video_info_update_requested', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('author', 'permlink', name='posts_unique')
    )
    op.create_index('posts_idx_0', 'posts', ['author', 'permlink'], unique=False)
    op.create_index('posts_idx_1', 'posts', ['trending_score'], unique=False)
    op.create_index('posts_idx_10', 'posts', ['category', sa.text('created DESC')], unique=False)
    op.create_index('posts_idx_11', 'posts', ['pending_video_info_update', 'video_info_update_requested'], unique=False, postgresql_where=sa.text('pending_video_info_update'))
    op.create_index('posts_idx_12', 'posts', ['pending_steem_info_update', 'steem_info_update_requested'], unique=False, postgresql_where=sa.text('pending_steem_info_update'))
    op.create_index('posts_idx_2', 'posts', ['hot_score'], unique=False)
    op.create_index('posts_idx_4', 'posts', ['pending_payout_value'], unique=False)
    op.create_index('posts_idx_5', 'posts', ['category', 'trending_score'], unique=False)
    op.create_index('posts_idx_6', 'posts', ['category', 'hot_score'], unique=False)
    op.create_index('posts_idx_7', 'posts', ['category', 'other_score'], unique=False)
    op.create_index('posts_idx_8', 'posts', ['category', 'pending_payout_value'], unique=False)
    op.create_index('posts_idx_9', 'posts', [sa.text('created DESC')], unique=False)
    op.create_table(
        'steem_accounts',
        sa.Column('author', sa.String(), nullable=False),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('author')
    )
    op.create_table(
        'channels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('auto_add_criteria', sa.JSON(), nullable=True),
        sa.Column('benefactor_info', sa.JSON(), nullable=True),
        sa.Column('default_post_sort_order', sa.JSON(), nullable=True),
        sa.Column('last_auto_added', sa.DateTime(), nullable=False),
        sa.Column('pending_auto_add', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['account'], ['accounts.owner'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'channel_posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.Integer(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('default_position', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
        sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_posts')
    op.drop_table('channels')
    op.drop_table('steem_accounts')
    op.drop_index('posts_idx_9', table_name='posts')
    op.drop_index('posts_idx_8', table_name='posts')
    op.drop_index('posts_idx_7', table_name='posts')
    op.drop_index('posts_idx_6', table_name='posts')
    op.drop_index('posts_idx_5', table_name='posts')
    op.drop_index('posts_idx_4', table_name='posts')
    op.drop_index('posts_idx_2', table_name='posts')
    op.drop_index('posts_idx_12', table_name='posts')
    op.drop_index('posts_idx_11', table_name='posts')
    op.drop_index('posts_idx_10', table_name='posts')
    op.drop_index('posts_idx_1', table_name='posts')
    op.drop_index('posts_idx_0', table_name='posts')
    op.drop_table('posts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
